#!/usr/bin/env bash
set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"

if [[ -f "${_path}/_dm-helper.sh" ]]; then
# shellcheck disable=SC1090,SC1091
    source "${_path}/_dm-helper.sh"
else
# shellcheck disable=SC1090
    echo 'No helper-script found'
fi

# Script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
    declare -A f_list

    for font in $(fc-list | awk '{print $1}'| sed 's/://g' | grep -i "\.ttf$\|\.otf$\|\.TTF$")
    do
        #index=$(echo "$font" | rev | cut -d'/' -f 1 | cut -d '.' -f 2 | rev)
        index=$(basename $font | sed 's/\..3$//')
        f_list[$index]="$font"
    done

    choice="$(printf "%s\n" ${!f_list[@]} | ${DMENU} 'Choose font for preview: ')"
    [[ -n $choice ]] && display "${f_list[$choice]}"
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
